apiVersion: v1
kind: Secret
metadata:
  name: ceylon-tea-secrets
  labels:
    app: ceylon-tea
stringData:
  POSTGRES_DB: ceylon_tea_db
  POSTGRES_USER: tea_admin
  POSTGRES_PASSWORD: tea_secure_pass_2024
  DATABASE_URL: postgresql://tea_admin:tea_secure_pass_2024@ceylon-tea-db:5432/ceylon_tea_db
  TOMORROWIO_API_KEY: ""
  TOMORROWIO_BASE_URL: "https://api.tomorrow.io/v4"
  PF_WINDY_API_KEY: ""
  MP_WINDY_API_KEY: ""
  METEOSOURCE_API_KEY: ""
  WEATHER_CACHE_TTL: "300"
